/*
    TABLE_CREATION_SCRIPTS.sql
    project i2i systems telco case study
*/

DROP TABLE MONTHLY_STATS CASCADE CONSTRAINTS;
DROP TABLE CUSTOMERS CASCADE CONSTRAINTS;
DROP TABLE TARIFFS CASCADE CONSTRAINTS;

CREATE TABLE TARIFFS (
    TARIFF_ID NUMBER,
    NAME VARCHAR2(100) NOT NULL,
    MONTHLY_FEE NUMBER(10,2) NOT NULL,
    DATA_LIMIT NUMBER(10,2) NOT NULL,
    MINUTE_LIMIT NUMBER(10) NOT NULL,
    SMS_LIMIT NUMBER(10) NOT NULL,

    CONSTRAINT PK_TARIFFS PRIMARY KEY (TARIFF_ID),
    CONSTRAINT UQ_TARIFFS_NAME UNIQUE (NAME),
    CONSTRAINT CHK_TARIFFS_MONTHLY_FEE CHECK (MONTHLY_FEE >= 0),
    CONSTRAINT CHK_TARIFFS_DATA_LIMIT CHECK (DATA_LIMIT >= 0),
    CONSTRAINT CHK_TARIFFS_MINUTE_LIMIT CHECK (MINUTE_LIMIT >= 0),
    CONSTRAINT CHK_TARIFFS_SMS_LIMIT CHECK (SMS_LIMIT >= 0)
);

CREATE TABLE CUSTOMERS (
    CUSTOMER_ID NUMBER,
    NAME VARCHAR2(100) NOT NULL,
    CITY VARCHAR2(100) NOT NULL,
    SIGNUP_DATE DATE NOT NULL,
    TARIFF_ID NUMBER NOT NULL,

    CONSTRAINT PK_CUSTOMERS PRIMARY KEY (CUSTOMER_ID),
    CONSTRAINT FK_CUSTOMERS_TARIFFS
        FOREIGN KEY (TARIFF_ID)
        REFERENCES TARIFFS (TARIFF_ID)
);

CREATE TABLE MONTHLY_STATS (
    ID NUMBER,
    CUSTOMER_ID NUMBER NOT NULL,
    DATA_USAGE NUMBER(10,2) NOT NULL,
    MINUTE_USAGE NUMBER(10) NOT NULL,
    SMS_USAGE NUMBER(10) NOT NULL,
    PAYMENT_STATUS VARCHAR2(20) NOT NULL,

    CONSTRAINT PK_MONTHLY_STATS PRIMARY KEY (ID),
    CONSTRAINT FK_MONTHLY_STATS_CUSTOMERS
        FOREIGN KEY (CUSTOMER_ID)
        REFERENCES CUSTOMERS (CUSTOMER_ID),
    CONSTRAINT UQ_MONTHLY_STATS_CUSTOMER UNIQUE (CUSTOMER_ID),
    CONSTRAINT CHK_MONTHLY_STATS_DATA_USAGE CHECK (DATA_USAGE >= 0),
    CONSTRAINT CHK_MONTHLY_STATS_MINUTE_USAGE CHECK (MINUTE_USAGE >= 0),
    CONSTRAINT CHK_MONTHLY_STATS_SMS_USAGE CHECK (SMS_USAGE >= 0),
    CONSTRAINT CHK_MONTHLY_STATS_PAYMENT
        CHECK (PAYMENT_STATUS IN ('PAID', 'UNPAID', 'LATE'))
);

CREATE INDEX IDX_CUSTOMERS_TARIFF_ID
ON CUSTOMERS (TARIFF_ID);

CREATE INDEX IDX_CUSTOMERS_CITY
ON CUSTOMERS (CITY);

CREATE INDEX IDX_CUSTOMERS_SIGNUP_DATE
ON CUSTOMERS (SIGNUP_DATE);

CREATE INDEX IDX_MONTHLY_STATS_CUSTOMER_ID
ON MONTHLY_STATS (CUSTOMER_ID);

CREATE INDEX IDX_MONTHLY_STATS_PAYMENT_STATUS
ON MONTHLY_STATS (PAYMENT_STATUS);

/*
    basic validation queries after table creation
   queries can be executed after importing the CSV files
*/

SELECT COUNT(*) AS tariff_count FROM TARIFFS;
SELECT COUNT(*) AS customer_count FROM CUSTOMERS;
SELECT COUNT(*) AS monthly_stats_count FROM MONTHLY_STATS;
